"""add_job_level

Revision ID: 1bac96816b55
Revises: 3380dcc967dd
Create Date: 2026-04-13 13:54:04.559122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bac96816b55'
down_revision: Union[str, Sequence[str], None] = '3380dcc967dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('level', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_jobs_level'), 'jobs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_level'), table_name='jobs')
    op.drop_column('jobs', 'level')
    # ### end Alembic commands ###
