"""add_pipeline_stages

Revision ID: 3380dcc967dd
Revises: b04b21dc39dd
Create Date: 2026-04-13 10:56:52.852586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3380dcc967dd'
down_revision: Union[str, Sequence[str], None] = 'b04b21dc39dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'resume_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('APPLIED', 'SHORTLISTED', 'HR_INTERVIEW', 'TECH_INTERVIEW', 'OFFER', 'REJECTED', name='applicationstatus'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.add_column('jobs', sa.Column('pipeline_stages_json', sa.Text(), nullable=True))
    op.alter_column('jobs', 'org_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'org_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('jobs', 'pipeline_stages_json')
    op.alter_column('applications', 'status',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('APPLIED', 'SHORTLISTED', 'HR_INTERVIEW', 'TECH_INTERVIEW', 'OFFER', 'REJECTED', name='applicationstatus'),
               existing_nullable=False)
    op.alter_column('applications', 'resume_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
