"""add ai limits to users

Revision ID: 77c5b41aba6b
Revises: b072e3bb4b1f
Create Date: 2026-04-27 18:30:41.800599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c5b41aba6b'
down_revision: Union[str, Sequence[str], None] = 'b072e3bb4b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('ai_used', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_quota_reset', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_quota_reset')
    op.drop_column('users', 'ai_used')
    op.drop_column('users', 'ai_quota')
    # ### end Alembic commands ###
