"""add new columns

Revision ID: b04b21dc39dd
Revises: 
Create Date: 2026-04-07 23:01:11.852757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04b21dc39dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('documents', sa.Column('resume_id', sa.String(length=64), nullable=True))
    # op.add_column('documents', sa.Column('document_role', sa.String(length=32), nullable=False, server_default='unknown'))
    # op.create_index(op.f('ix_documents_resume_id'), 'documents', ['resume_id'], unique=False)
    # op.create_foreign_key(None, 'documents', 'resumes', ['resume_id'], ['resume_id'])
    # op.add_column('resumes', sa.Column('language', sa.String(length=16), nullable=False, server_default='unknown'))
    # op.add_column('resumes', sa.Column('title', sa.String(length=255), nullable=True))
    # op.add_column('resumes', sa.Column('source_type', sa.String(length=32), nullable=False, server_default='unknown'))
    # op.add_column('resumes', sa.Column('source_document_id', sa.String(length=64), nullable=True))
    # op.add_column('resumes', sa.Column('generated_document_id', sa.String(length=64), nullable=True))
    # op.add_column('resumes', sa.Column('source_resume_id', sa.String(length=64), nullable=True))
    # op.add_column('resumes', sa.Column('profile_snapshot_json', sa.Text(), nullable=True))
    # op.add_column('resumes', sa.Column('generation_status', sa.String(length=32), nullable=False, server_default='pending'))
    # op.add_column('resumes', sa.Column('valid_until', sa.String(length=20), nullable=True))
    # op.add_column('resumes', sa.Column('job_description', sa.Text(), nullable=True))
    # op.create_index(op.f('ix_resumes_generated_document_id'), 'resumes', ['generated_document_id'], unique=False)
    # op.create_index(op.f('ix_resumes_person_id'), 'resumes', ['person_id'], unique=False)
    # op.create_index(op.f('ix_resumes_source_document_id'), 'resumes', ['source_document_id'], unique=False)
    # op.create_index(op.f('ix_resumes_source_resume_id'), 'resumes', ['source_resume_id'], unique=False)
    # op.create_foreign_key(None, 'resumes', 'documents', ['source_document_id'], ['document_id'])
    # op.create_foreign_key(None, 'resumes', 'documents', ['generated_document_id'], ['document_id'])
    # op.create_foreign_key(None, 'resumes', 'resumes', ['source_resume_id'], ['resume_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'resumes', type_='foreignkey')
    # op.drop_constraint(None, 'resumes', type_='foreignkey')
    # op.drop_constraint(None, 'resumes', type_='foreignkey')
    # op.drop_index(op.f('ix_resumes_source_resume_id'), table_name='resumes')
    # op.drop_index(op.f('ix_resumes_source_document_id'), table_name='resumes')
    # op.drop_index(op.f('ix_resumes_person_id'), table_name='resumes')
    # op.drop_index(op.f('ix_resumes_generated_document_id'), table_name='resumes')
    # op.drop_column('resumes', 'job_description')
    # op.drop_column('resumes', 'valid_until')
    # op.drop_column('resumes', 'generation_status')
    # op.drop_column('resumes', 'profile_snapshot_json')
    # op.drop_column('resumes', 'source_resume_id')
    # op.drop_column('resumes', 'generated_document_id')
    # op.drop_column('resumes', 'source_document_id')
    # op.drop_column('resumes', 'source_type')
    # op.drop_column('resumes', 'title')
    # op.drop_column('resumes', 'language')
    # op.drop_constraint(None, 'documents', type_='foreignkey')
    # op.drop_index(op.f('ix_documents_resume_id'), table_name='documents')
    # op.drop_column('documents', 'document_role')
    # op.drop_column('documents', 'resume_id')
    # # ### end Alembic commands ###