"""add requirements column to jobs

Revision ID: b072e3bb4b1f
Revises: fa9c519b174f
Create Date: 2026-04-20 21:58:34.771841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b072e3bb4b1f'
down_revision: Union[str, Sequence[str], None] = 'fa9c519b174f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('requirements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'requirements')
    # ### end Alembic commands ###
