"""add privacy sharing fields to person

Revision ID: fa9c519b174f
Revises: ac1a6df1adf1
Create Date: 2026-04-15 21:15:17.841256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9c519b174f'
down_revision: Union[str, Sequence[str], None] = 'ac1a6df1adf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('visibility_level', sa.String(length=32), nullable=False, server_default='public'))
    op.add_column('persons', sa.Column('shared_with_org_ids_json', sa.Text(), nullable=True))
    op.add_column('persons', sa.Column('public_url_slug', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_persons_public_url_slug'), 'persons', ['public_url_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_public_url_slug'), table_name='persons')
    op.drop_column('persons', 'public_url_slug')
    op.drop_column('persons', 'shared_with_org_ids_json')
    op.drop_column('persons', 'visibility_level')
    # ### end Alembic commands ###
